server:
  port: 8082
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vod_test}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_QUERY:true}

services:
  episodeService:
    baseUrl: ${EPISODE_SERVICE_BASE_URL:http://localhost:8083}
    timeOut: 10
    getAllEpisodeBySeasonId: "/episodes/view/season/{seasonId}"